FROM centos
RUN yum install java-11-openjdk-devel -y

RUN rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key && cd /etc/yum.repos.d/ && curl -O https://pkg.jenkins.io/redhat-stable/jenkins.repo

RUN yum install jenkins -y

RUN yum install initscripts -y

EXPOSE 8080

RUN /etc/rc.d/init.d/jenkins start

CMD ["java", "-jar", "/usr/lib/jenkins/jenkins.war"]

